server:
  port: 8080
  servlet:
    context-path: "/coffee"
spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: "jdbc:postgresql://localhost:5432/e-commerce"
    username: postgres
    password: postgres


