server:
  port: 8080
  servlet:
    context-path: "/coffee"
spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: "jdbc:postgresql://localhost:5432/e-commerce"
    username: postgres
    password: postgres
jwt:
  signerKey: "b57S8EwSsiOILajeTo/taG+vZlkrgZ5klwp+7+Fw6Vt1ZAnh1VifFh10H/mReLfr"
  valid-duration: 3600
  refreshable-duration: 36000
